name: Code quality
on:
  pull_request:
    branches:
      - main
jobs:
  qodana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm test:ci
      - name: Create QODANA folder
        run: mkdir .qodana
      - name: Move coverage folder to QODANA
        run: mv coverage .qodana/coverage
      - name: Archive coverage data
        uses: actions/upload-artifact@v3
        with:
          name: vitest-coverage-data
          path: .qodana/coverage
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2022.3.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
